name: WORK labs
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2593
title: WORK Labs - Always Thinking
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bfdaf4'
    - '#284872'
    - '#6f90bc'
    - '#a3b2bf'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
